### ISSUE TITLE
Creation of ADFz Learning Resources Page

### ISSUE THREAD

**Issue by shabbirmoledina** [IBM/mainframe-downloads#14]
1) Please create a new page for me, by copying over the content from https://ibm.biz/zDevOpsLearningResources. Let me know when you have the skeleton in place, and I can help fix a couple of the links that may be pointing to wrong ones.

2) On this page (https://ibm.github.io/mainframe-downloads/Training/Training.html), can we have a new section created below **Training**, please call it **Resources**.

Create a new tile called **ADFz Learning Resources** and link it to the new page (created in item 1 above)

**Comment by jerryxz-ibm** [comment]
@shabbirmoledina I've created a draft page at: https://ibm.github.io/mainframe-downloads/Training/adfz-learning-resources.html
Please note the page style might be different from the original one due to contents are wrapped inside the MDC page template (e.g. sections are collapsed with a "+" icon rather than fully expanded). So please have a review for it. If you think everything's good, I can expose it with a resource section created on the main training page.

**Comment by jerryxz-ibm** [comment]
This page is reviewed and all necessary links are created according to the comments.
